### ISSUE TITLE
Bugs fixed with PR #11

### ISSUE THREAD

**Issue by moisesbr-dw** [dwp-forge/qna#12]
I submitted PR #11 which corrects two bugs.
Please consider merging them.
Thanks!

**Comment by dwp-forge** [comment]
Yeah, I'm looking into it. Sorry for the delay, but it has been a long while since I touched this code and the section link bug is tougher than I thought. I'm still working on a proper fix.

**Comment by moisesbr-dw** [comment]
I've updated my test to include two section titles with the same name.
My proposed solution doesn't work in this case, it generates the same link.
I will update my PR.

**Comment by moisesbr-dw** [comment]
I did another commit to generate different links for sections with the same name.
First link (anchor) is simply "section_name".
The following are "section_name1", "section_name2" etc.
Hope this helps!
Thanks.

**Comment by moisesbr-dw** [comment]
The PR referred here was split into #13 and #14.
