### ISSUE TITLE
Margin of the TOC

### ISSUE THREAD

**Issue by MvErven** [dwp-forge/qna#18]
I've been playing for two days with this QnA. Looks good. Simplicity is key.

The "~~QNA~~" creates a list. Only the margins are zero. 
Can this be altered? 

I'm no expert in CSS. 
Which CSS should be altered? And which line?
Thanks in Advance.

![margins_toc_qna](https://user-images.githubusercontent.com/17900348/28709958-9dec646e-7382-11e7-85ea-d26a7060703c.png)

**Comment by dwp-forge** [comment]
Add the following into your [`conf/userall.css`](https://www.dokuwiki.org/devel:css#user_styles):
``` css
div.dokuwiki div.qna-toc {
  margin-left: 2em;
}
```

You might need to purge [DokuWiki cache](https://www.dokuwiki.org/devel:caching#location) after that.

**Comment by MvErven** [comment]
Thanks for the fast reply. case closed.
