### ISSUE TITLE
Multibyte characters are not set correctly in the name attribute of "a" tag.

### ISSUE THREAD

**Issue by tanakakz-alpha** [dwp-forge/qna#19]
When qna 's title is mixed with alphanumeric characters and multibyte characters, multibyte characters may be disconnected halfway and set to name attribute in some cases.
As a result, links from the list do not work properly.

**Comment by dwp-forge** [comment]
Fixed in [release of 2017-09-25](https://github.com/dwp-forge/qna/releases/tag/v.2017-09-25).
