### ISSUE TITLE
Problem with PHP8

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [dwp-forge/qna#21]
Hi,

after updating the dokuwiki server to PHP8 the qna plugin fails with the following error message when I go to the konfig page of the admin console:

```
dokuwiki\Exception\FatalException: Array and string offset access syntax with curly braces is no longer supported
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the qna plugin.
```
What can I do?

Best regards
Juergen

**Comment by dwp-forge** [comment]
What makes you think that QnA is to blame?

Which version of the plugin do you use?

Did you try to disable the plugin?

**Comment by Juergen-aus-Zuendorf** [comment]
What makes you think that QnA is to blame?
→ The error message contains the following text "It might be a problem in the qna plugin."

Which version of the plugin do you use?
→ Version 2017-09-25

Did you try to disable the plugin?
→ Dokuwiki didn't start, so I had to delete the qna-folder to get dokuwiki working again. Only disabling wasn't possible.

**Comment by dwp-forge** [comment]
I tried QnA 2017-09-25 with DokuWiki 2022-06-26 on PHP 8.1.7, and I don't see the issue you have reported.

Could you please check your `dokuwiki/data/log` directory to see if there are more detailed logs?

**Comment by Juergen-aus-Zuendorf** [comment]
Here is the relevant excerpt of the log file:
```
dokuwiki\Exception\FatalException: Array and string offset access syntax with curly braces is no longer supported
/var/www/html/wiki/lib/plugins/qna/syntax/block.php(62)
#0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
#1 {main}
```
