### ISSUE TITLE
require(action.php) is deprecated

### ISSUE THREAD

**Issue by fjf2002** [dwp-forge/qna#22]
My deprecated log gets spammed with messages

> require(action.php) is deprecated. It was called from require() in /srv/www/htdocs/doku/lib/plugins/qna/action.php:14 Autoloading should be used instead!

cf. https://github.com/dwp-forge/qna/blob/4aee6fa3ad154ce2abd8e64b89a5954336c2447a/action.php#L14

**Comment by dwp-forge** [comment]
Fixed in [v.2023-06-18](https://github.com/dwp-forge/qna/releases/tag/v.2023-06-18).
